# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 762)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(240, 140, 500, 500))
        self.graphicsView.setObjectName("graphicsView")
        self.chooseButton = QtWidgets.QPushButton(self.centralwidget)
        self.chooseButton.setGeometry(QtCore.QRect(0, 0, 200, 32))
        self.chooseButton.setObjectName("chooseButton")
        self.edgeButton = QtWidgets.QPushButton(self.centralwidget)
        self.edgeButton.setGeometry(QtCore.QRect(0, 90, 200, 32))
        self.edgeButton.setObjectName("edgeButton")
        self.geodilationButton = QtWidgets.QPushButton(self.centralwidget)
        self.geodilationButton.setGeometry(QtCore.QRect(0, 130, 200, 32))
        self.geodilationButton.setObjectName("geodilationButton")
        self.geoerosionButton = QtWidgets.QPushButton(self.centralwidget)
        self.geoerosionButton.setGeometry(QtCore.QRect(0, 170, 200, 32))
        self.geoerosionButton.setObjectName("geoerosionButton")
        self.obrButton = QtWidgets.QPushButton(self.centralwidget)
        self.obrButton.setGeometry(QtCore.QRect(0, 210, 200, 32))
        self.obrButton.setObjectName("obrButton")
        self.cbrButton = QtWidgets.QPushButton(self.centralwidget)
        self.cbrButton.setGeometry(QtCore.QRect(0, 250, 200, 32))
        self.cbrButton.setObjectName("cbrButton")
        self.gradientButton = QtWidgets.QPushButton(self.centralwidget)
        self.gradientButton.setGeometry(QtCore.QRect(0, 290, 200, 32))
        self.gradientButton.setObjectName("gradientButton")
        self.originButton = QtWidgets.QPushButton(self.centralwidget)
        self.originButton.setGeometry(QtCore.QRect(0, 30, 200, 32))
        self.originButton.setObjectName("originButton")
        self.kernelText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.kernelText.setEnabled(False)
        self.kernelText.setGeometry(QtCore.QRect(30, 380, 151, 131))
        self.kernelText.setObjectName("kernelText")
        self.kernelLabel = QtWidgets.QLabel(self.centralwidget)
        self.kernelLabel.setEnabled(False)
        self.kernelLabel.setGeometry(QtCore.QRect(30, 320, 171, 61))
        self.kernelLabel.setWordWrap(True)
        self.kernelLabel.setObjectName("kernelLabel")
        self.standardButton = QtWidgets.QPushButton(self.centralwidget)
        self.standardButton.setEnabled(False)
        self.standardButton.setGeometry(QtCore.QRect(20, 560, 150, 32))
        self.standardButton.setObjectName("standardButton")
        self.externalButton = QtWidgets.QPushButton(self.centralwidget)
        self.externalButton.setEnabled(False)
        self.externalButton.setGeometry(QtCore.QRect(20, 600, 150, 32))
        self.externalButton.setObjectName("externalButton")
        self.internalButton = QtWidgets.QPushButton(self.centralwidget)
        self.internalButton.setEnabled(False)
        self.internalButton.setGeometry(QtCore.QRect(20, 640, 150, 32))
        self.internalButton.setObjectName("internalButton")
        self.binaryButton = QtWidgets.QPushButton(self.centralwidget)
        self.binaryButton.setGeometry(QtCore.QRect(0, 60, 200, 32))
        self.binaryButton.setObjectName("binaryButton")
        self.repeatLabel = QtWidgets.QLabel(self.centralwidget)
        self.repeatLabel.setEnabled(False)
        self.repeatLabel.setGeometry(QtCore.QRect(240, 640, 91, 51))
        self.repeatLabel.setWordWrap(True)
        self.repeatLabel.setObjectName("repeatLabel")
        self.repeatText = QtWidgets.QLineEdit(self.centralwidget)
        self.repeatText.setEnabled(False)
        self.repeatText.setGeometry(QtCore.QRect(350, 650, 113, 21))
        self.repeatText.setObjectName("repeatText")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setEnabled(False)
        self.okButton.setGeometry(QtCore.QRect(490, 650, 113, 32))
        self.okButton.setObjectName("okButton")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 510, 171, 41))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 10, 481, 111))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 791, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.chooseButton.clicked.connect(MainWindow.choose_image)
        self.edgeButton.clicked.connect(MainWindow.edge_detector)
        self.originButton.clicked.connect(MainWindow.display_origin)
        self.geodilationButton.clicked.connect(MainWindow.geo_dilation)
        self.geoerosionButton.clicked.connect(MainWindow.geo_erosion)
        self.obrButton.clicked.connect(MainWindow.open_reconstruct)
        self.cbrButton.clicked.connect(MainWindow.close_reconstruct)
        self.gradientButton.clicked.connect(MainWindow.morph_gradient)
        self.standardButton.clicked.connect(MainWindow.display_standard_grad)
        self.externalButton.clicked.connect(MainWindow.display_external_grad)
        self.internalButton.clicked.connect(MainWindow.display_internal_grad)
        self.binaryButton.clicked.connect(MainWindow.display_binary)
        self.okButton.clicked.connect(MainWindow.display_ok)
        self.pushButton.clicked.connect(MainWindow.generate_kernel)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chooseButton.setText(_translate("MainWindow", "choose image"))
        self.edgeButton.setText(_translate("MainWindow", "edge detection"))
        self.geodilationButton.setText(_translate("MainWindow", "condition dilation"))
        self.geoerosionButton.setText(_translate("MainWindow", "condition erosion"))
        self.obrButton.setText(_translate("MainWindow", "opening by reconstruction"))
        self.cbrButton.setText(_translate("MainWindow", "closing by reconstruction"))
        self.gradientButton.setText(_translate("MainWindow", "morphological gradient"))
        self.originButton.setText(_translate("MainWindow", "original image"))
        self.kernelLabel.setText(_translate("MainWindow", "Enter kernel in an array format:(default=[[1,1,1],[1,1,1],[1,1,1]])"))
        self.standardButton.setText(_translate("MainWindow", "standard"))
        self.externalButton.setText(_translate("MainWindow", "external"))
        self.internalButton.setText(_translate("MainWindow", "internal"))
        self.binaryButton.setText(_translate("MainWindow", "binary image"))
        self.repeatLabel.setText(_translate("MainWindow", "repeat times:(default=3)"))
        self.okButton.setText(_translate("MainWindow", "OK"))
        self.pushButton.setText(_translate("MainWindow", "Generate 11x11 kernel"))
        self.label.setText(_translate("MainWindow", "pyqt5显示界面有点问题，请助教在点击任意按钮后切换窗口到其他地方再切换回来，否则界面的更新不会显示出来。左上按钮选择对应功能后需要在左下按钮进行选择或输入对应参数才会开始对图像处理。"))
