# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 762)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(240, 40, 500, 500))
        self.graphicsView.setObjectName("graphicsView")
        self.chooseButton = QtWidgets.QPushButton(self.centralwidget)
        self.chooseButton.setGeometry(QtCore.QRect(0, 10, 200, 32))
        self.chooseButton.setObjectName("chooseButton")
        self.edgeButton = QtWidgets.QPushButton(self.centralwidget)
        self.edgeButton.setGeometry(QtCore.QRect(0, 90, 200, 32))
        self.edgeButton.setObjectName("edgeButton")
        self.geodilationButton = QtWidgets.QPushButton(self.centralwidget)
        self.geodilationButton.setGeometry(QtCore.QRect(0, 130, 200, 32))
        self.geodilationButton.setObjectName("geodilationButton")
        self.geoerosionButton = QtWidgets.QPushButton(self.centralwidget)
        self.geoerosionButton.setGeometry(QtCore.QRect(0, 170, 200, 32))
        self.geoerosionButton.setObjectName("geoerosionButton")
        self.obrButton = QtWidgets.QPushButton(self.centralwidget)
        self.obrButton.setGeometry(QtCore.QRect(0, 210, 200, 32))
        self.obrButton.setObjectName("obrButton")
        self.cbrButton = QtWidgets.QPushButton(self.centralwidget)
        self.cbrButton.setGeometry(QtCore.QRect(0, 250, 200, 32))
        self.cbrButton.setObjectName("cbrButton")
        self.gradientButton = QtWidgets.QPushButton(self.centralwidget)
        self.gradientButton.setGeometry(QtCore.QRect(0, 290, 200, 32))
        self.gradientButton.setObjectName("gradientButton")
        self.originButton = QtWidgets.QPushButton(self.centralwidget)
        self.originButton.setGeometry(QtCore.QRect(0, 50, 200, 32))
        self.originButton.setObjectName("originButton")
        self.sigmaLabel = QtWidgets.QLabel(self.centralwidget)
        self.sigmaLabel.setEnabled(False)
        self.sigmaLabel.setGeometry(QtCore.QRect(20, 350, 101, 51))
        self.sigmaLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sigmaLabel.setScaledContents(False)
        self.sigmaLabel.setWordWrap(True)
        self.sigmaLabel.setObjectName("sigmaLabel")
        self.edgeOkButton = QtWidgets.QPushButton(self.centralwidget)
        self.edgeOkButton.setEnabled(False)
        self.edgeOkButton.setGeometry(QtCore.QRect(50, 510, 113, 32))
        self.edgeOkButton.setObjectName("edgeOkButton")
        self.threshLabel = QtWidgets.QLabel(self.centralwidget)
        self.threshLabel.setEnabled(False)
        self.threshLabel.setGeometry(QtCore.QRect(20, 420, 101, 41))
        self.threshLabel.setObjectName("threshLabel")
        self.threshLowLabel = QtWidgets.QLabel(self.centralwidget)
        self.threshLowLabel.setEnabled(False)
        self.threshLowLabel.setGeometry(QtCore.QRect(20, 440, 111, 31))
        self.threshLowLabel.setWordWrap(True)
        self.threshLowLabel.setObjectName("threshLowLabel")
        self.threshHighLabel = QtWidgets.QLabel(self.centralwidget)
        self.threshHighLabel.setEnabled(False)
        self.threshHighLabel.setGeometry(QtCore.QRect(10, 480, 111, 31))
        self.threshHighLabel.setWordWrap(True)
        self.threshHighLabel.setObjectName("threshHighLabel")
        self.sigmaText = QtWidgets.QLineEdit(self.centralwidget)
        self.sigmaText.setGeometry(QtCore.QRect(130, 360, 61, 21))
        self.sigmaText.setObjectName("sigmaText")
        self.threshLowText = QtWidgets.QLineEdit(self.centralwidget)
        self.threshLowText.setGeometry(QtCore.QRect(130, 440, 61, 21))
        self.threshLowText.setObjectName("threshLowText")
        self.threshHighText = QtWidgets.QLineEdit(self.centralwidget)
        self.threshHighText.setGeometry(QtCore.QRect(130, 480, 61, 21))
        self.threshHighText.setObjectName("threshHighText")
        self.kernelText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.kernelText.setEnabled(False)
        self.kernelText.setGeometry(QtCore.QRect(130, 570, 151, 131))
        self.kernelText.setObjectName("kernelText")
        self.kernelLabel = QtWidgets.QLabel(self.centralwidget)
        self.kernelLabel.setEnabled(False)
        self.kernelLabel.setGeometry(QtCore.QRect(10, 570, 101, 101))
        self.kernelLabel.setWordWrap(True)
        self.kernelLabel.setObjectName("kernelLabel")
        self.standardButton = QtWidgets.QPushButton(self.centralwidget)
        self.standardButton.setEnabled(False)
        self.standardButton.setGeometry(QtCore.QRect(640, 580, 150, 32))
        self.standardButton.setObjectName("standardButton")
        self.externalButton = QtWidgets.QPushButton(self.centralwidget)
        self.externalButton.setEnabled(False)
        self.externalButton.setGeometry(QtCore.QRect(640, 620, 150, 32))
        self.externalButton.setObjectName("externalButton")
        self.internalButton = QtWidgets.QPushButton(self.centralwidget)
        self.internalButton.setEnabled(False)
        self.internalButton.setGeometry(QtCore.QRect(640, 660, 150, 32))
        self.internalButton.setObjectName("internalButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 791, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.chooseButton.clicked.connect(MainWindow.choose_image)
        self.edgeButton.clicked.connect(MainWindow.edge_detector)
        self.edgeOkButton.clicked.connect(MainWindow.display_edge)
        self.originButton.clicked.connect(MainWindow.display_origin)
        self.geodilationButton.clicked.connect(MainWindow.geo_dilation)
        self.geoerosionButton.clicked.connect(MainWindow.geo_erosion)
        self.obrButton.clicked.connect(MainWindow.open_reconstruct)
        self.cbrButton.clicked.connect(MainWindow.close_reconstruct)
        self.gradientButton.clicked.connect(MainWindow.morph_gradient)
        self.standardButton.clicked.connect(MainWindow.display_standard_grad)
        self.externalButton.clicked.connect(MainWindow.display_external_grad)
        self.internalButton.clicked.connect(MainWindow.display_internal_grad)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chooseButton.setText(_translate("MainWindow", "choose image"))
        self.edgeButton.setText(_translate("MainWindow", "edge detection"))
        self.geodilationButton.setText(_translate("MainWindow", "condition dilation"))
        self.geoerosionButton.setText(_translate("MainWindow", "condition erosion"))
        self.obrButton.setText(_translate("MainWindow", "opening by reconstruction"))
        self.cbrButton.setText(_translate("MainWindow", "closing by reconstruction"))
        self.gradientButton.setText(_translate("MainWindow", "morphological gradient"))
        self.originButton.setText(_translate("MainWindow", "original image"))
        self.sigmaLabel.setText(_translate("MainWindow", "Enter sigma for Gaussian filter:(default=3)"))
        self.edgeOkButton.setText(_translate("MainWindow", "OK"))
        self.threshLabel.setText(_translate("MainWindow", "Enter threshold:"))
        self.threshLowLabel.setText(_translate("MainWindow", "low(default=20)"))
        self.threshHighLabel.setText(_translate("MainWindow", "high(default=30)"))
        self.kernelLabel.setText(_translate("MainWindow", "Enter kernel in an array format:(default=[[1,1,1],[1,1,1],[1,1,1]])"))
        self.standardButton.setText(_translate("MainWindow", "standard gradient"))
        self.externalButton.setText(_translate("MainWindow", "external gradient"))
        self.internalButton.setText(_translate("MainWindow", "internal gradient"))
